repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        name: Format Python Code (black)
        files: '^(HS2|scripts)/.*\.py$'

  - repo: local
    hooks:
      - id: fprime-util-format
        name: Format Changed C++ Code (clang-format)
        entry: fprime-util
        language: system
        files: \.(c|h|cpp|hpp|fpp)$
        pass_filenames: true
        args: ["format", "-f"]
